# Generated by Django 5.2.7 on 2025-11-15 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredient_options_alter_recipe_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Количество ингредиента не может быть меньше 1.'), django.core.validators.MaxValueValidator(32000, message='Количество ингредиента не может превышать 32000.')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Время приготовления не может быть меньше 1 минуты.'), django.core.validators.MaxValueValidator(32000, message='Время приготовления не может превышать 32000 минут.')], verbose_name='Время приготовления (в минутах)'),
        ),
    ]
