# Generated by Django 5.2.7 on 2025-11-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_ingredientinrecipe_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_code',
            field=models.CharField(blank=True, max_length=6, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
